title: "hos"
description: "A Template For Frontend Expo Development."
baseurl: "/hos"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge